### ISSUE TITLE
Make plugin warn when syncing in something that isn't a place

### ISSUE THREAD

**Issue by LPGhatguy** [rojo-rbx/rojo#113]
The plugin tries to destroy the DataModel if you sync in a project that describes a model. That's no good, we should instead catch this case and warn.

Maybe the server should also issue a warning if you serve a non-DataModel project, since that generally doesn't make much sense!

**Comment by masteratminecraftpc2** [comment]
Piggy

**Comment by boatbomber** [comment]
Oh, this issue has gotten more important recently. The diff visualizer for sync confirmation errors when syncing a non-place because it assumes it can access `.Parent`, which fails a security level check.
![image](https://github.com/rojo-rbx/rojo/assets/40185666/2b27b281-78f4-4863-ad10-b025312559e2)

**Comment by steveprogramc** [comment]
Protection thanks.

**Comment by steveprogramc** [comment]
ok let go.
