### ISSUE TITLE
Support syncing .json files

### ISSUE THREAD

**Issue by Quenty** [rojo-rbx/rojo#148]
As a developer. I use json files to store data in my game. This has several benefits:

* JSON is easily deserialized to Lua tables by Roblox's HttpService:DecodeJSON()
* JSON files have good validation and syntax highlighting in many editors
* Easy to separate data from code
* Portability

By forcing .txt at the end of json files, I lose

* Syntax highlighting
* Validation tools
* Clean file names

Supporting .json endings to sync as string values is a natural extension of Rojo. JSON, past Lua, is a very standardized way to store data in Roblox.

**Comment by LPGhatguy** [comment]
Do you think that JSON should always sync as `StringValue` objects?

This problem is definitely solved by server plugins, which are written in Lua and should make this trivial. Besides that, we have two other options:

1. Treat the `.json` extension the same as `.txt` and sync it as `StringValue`. I'm nervous about this since it could paint us into a corner.
2. Add a configuration option to allow turning specific file types into `StrigValue` instances, which feels kind of narrow.

I'm sort of concerned since there are other kinds of JSON file we want to support syncing as not-`StringValue` instances, like `.model.json`, `.meta.json`, and `.project.json`.

When server plugins land, we anticipate that a plugin that would implement this feature could be as simple as:

```lua
local function process(file, instance)
	if instance == nil then
		return {
			ClassName = "StringValue",
			Name = file:basename(),
			Properties = {
				Value = {
					Type = "String",
					Value = file:contents(),
				},
			},
		}
	end
end

return {
	filePattern = "\\.json$",
	process = process,
}
```

**Comment by Quenty** [comment]
Server plugins are a viable option, I'm just worried it'll be painful to port these around everywhere. 

I would expect any .json to turn into a string value unless it has additional names like .project.json.

However, server plugins are potentially cleaner. I'd personally like to see this built into Rojo though.

**Comment by LPGhatguy** [comment]
Coming back to this issue. I think I've come to some new conclusions in the last year, and I think I'll pursue this feature for the next major release of Rojo.

I think the compatibility concerns I had before can be solved with a more relaxed breaking change policy. Rojo will be skipping version 1.0 and skipping straight to the 'large major version number' model, which gives us an opportunity every once in awhile to introduce slight breaking changes.

I think JSON files turning into `StringValue` objects is not quite right. Instead, I think it would make sense to turn JSON files into Lua `ModuleScript` instances in the same shape. This lines up with the behavior of importing JSON files in Node.js, and I think would be more useful overall.
