### ISSUE TITLE
Live-Syncing Unions

### ISSUE THREAD

**Issue by Kampfkarren** [rojo-rbx/rojo#161]
I don't know if this is an rbx-dom issue or a Rojo issue, but either way there's no way for unions to sync right now. Blocked externally (no way for plugins to recreate unions right now?).

**Comment by LPGhatguy** [comment]
Would love to do this eventually!

**Comment by tiffany352** [comment]
Is this actually blocked? There's APIs on the `plugin` object for this: https://developer.roblox.com/api-reference/function/Plugin/Union

**Comment by Kampfkarren** [comment]
Importing rbxm/rbxmx unions is, but I guess unioning un-unioned Parts/NegativeParts is not.

**Comment by LPGhatguy** [comment]
There is an API for creating unions with the plugin, see [`BasePart:UnionAsync`](https://developer.roblox.com/api-reference/function/BasePart/UnionAsync) and [`BasePart:SubtractAsync`](https://developer.roblox.com/api-reference/function/BasePart/SubtractAsync).

The problem is more about dealing with the data as it's stored on-disk and figuring out how to turn that into instances in real time. While we'll be able to use files built to disk to load unions, I'm skeptical that it's even possible to try to interpret that data, create parts in a plugin, and join them to match the original geometry.

**Comment by LPGhatguy** [comment]
For completeness, we know that we can solve this at least in one direction with #205.

**Comment by LPGhatguy** [comment]
I believe the only solution for this is going to be #205. We can open a new issue in the future if there are specific issues for unions, but until then, I think we should lump them in with similar instances.
