### ISSUE TITLE
Uninformative ClientError

### ISSUE THREAD

**Issue by jpatrickdill** [rojo-rbx/rojo#203]
Whenever I attempt to connect from Studio, I get the following error:
```
13:48:20.494 - [Rojo-Warn] Rojo session terminated because of an error:
13:48:20.496 - [Rojo-Warn] ClientError
```
I have no way to figure out the issue and fix my configuration because this tells me nothing about what caused the error.

**Comment by LPGhatguy** [comment]
Oops, that's a terrible error message. Thanks for the report!

This error happens when the plugin sends a request that the server thinks is malformed. I should update the HTTP handling code to dump the response into the output so that there's at least a hint to what's wrong.

`ClientError` definitely isn't a user error, and it should be labeled in the output more clearly as a Rojo bug, most likely.

**Comment by LPGhatguy** [comment]
The `master` branch should now have much more informative errors when issues like this happen.
