### ISSUE TITLE
Rojo pathing issue with "." and "../path"

### ISSUE THREAD

**Issue by axia-roblox** [rojo-rbx/rojo#261]
When running rojo serve on a project.json file, rojo thinks a valid path doesn't exist (when in fact it does).

```lua
"ContainingFolder": {
    "$path": "."
},

"SomeValidPath": {
    "$path": "../SomeValidPath"
}
```

This seems to function as a workaround:

```lua
"ContainingFolder": {
    "$path": "../ContainingFolder"
},

"SomeValidPath": {
    "$path": "../SomeValidPath"
}
```

**Comment by LPGhatguy** [comment]
Starting in Rojo 6.0, the first entry is no longer valid in Rojo due to project composition becoming a feature.

I wasn't able to reproduce the other case involving `..`. I don't think I understand the difference in the second path for the two examples. If you run into this issue again on newer versions of Rojo, feel free to create a new issue!
