### ISSUE TITLE
Bad Color3/other array values in *.project.json file does not give specific error

### ISSUE THREAD

**Issue by NobleDraconian** [rojo-rbx/rojo#288]
Currently, as of version `0.5.3`, rojo does not give a specific error if you specify a bad array-based value in your project configuration file, such as a Color3 value.
```json
"Lighting" : {
	"$className" : "Lighting",
	"$properties" :  {
		"Technology" : "ShadowMap",
		"ClockTime" : 12,
		"GeographicLatitude" : 21,
		"Brightness" : 2,
		"ExposureCompensation" : 0,
		"Ambient" : [0,0,0],
		"OutdoorAmbient" : [0.50196078431373,0.50196078431373,0.50196078431373],
		"ColorShift_Bottom" : [0,0,0],
		"ColorShift_Top" : [0,0,0],
		"FogColor" : [0.75294117647059], //THIS LINE WILL GIVE A VAGUE ERROR
		"FogEnd" : 10000,
		"FogStart" : 0,
		"LegacyOutlines" : false,
		"GlobalShadows" : true,
		"ShadowSoftness" : 0
	}
},
```

The `FogColor` line in a project file will cause the following error to be spit from rojo:
`[ERROR rojo] Project load error: JSON error: invalid length 1, expected sequence of length 2, 3, 4, or 12 at line <line> column <column> in path <PathToFile>\default.project.json`
It should also be noted that `<line>` will be the last line of the file.

Rojo should be able to identify specific errors like these and point to the exact line number where the error took place, to save the developer confusion as to what the issue is. It should also give more concise error messages, such as `"Expected 3 color values for 'PropertyName', got 1 instead"`.

**Comment by LPGhatguy** [comment]
This error message happens because there are no values in Roblox that can be represented by an array with a single number.

At this stage, data hasn't even made it to Rojo yet, and we don't know that this property should be a `Color3` yet. This is currently in the domain of [rbx-dom](https://github.com/rojo-rbx/rbx-dom), which I've been doing some pretty large refactoring work on. It might be possible to fix this issue there.

Not having a correct line number is weird. I'm not sure if that's our bug or if it's something funny in serde-json, the JSON library we're using.

**Comment by LPGhatguy** [comment]
Error messages for this should be a bit better now on the master branch. This will ship as part of Rojo 7.
