### ISSUE TITLE
Rojo encountered an unknown error: httperror: connectfail

### ISSUE THREAD

**Issue by Hexlinee** [rojo-rbx/rojo#289]
Whenever I try to connect from Roblox Studio this appears on the output.

**Comment by LPGhatguy** [comment]
Hello, thanks for the issue report.

I'll need some more information to try to help you figure out what's going on:

* What version of the Rojo **server** and **plugin** are you running?
* Do you have HTTP enabled in your place?
* What address/port are you trying to connect to in the plugin?

In general, these kinds of errors happen because of user misconfiguration. We should improve the messaging around them, but that may be a separate issue.

**Comment by Hexlinee** [comment]
I think I use the latest version of Rojo.
I have http Enabled.
I am trying to connect to 34872.

**Comment by Hexlinee** [comment]
I am using Roblox Plugin 0.5.3

**Comment by RegularTetragon** [comment]
I second this, looking for a workaround.

**Comment by Dekkonot** [comment]
If anyone encounters this issue, please open a new one.
