### ISSUE TITLE
Rojo server crash: thread '<unnamed>' panicked at 'called `Result::unwrap()

### ISSUE THREAD

**Issue by FableRBX** [rojo-rbx/rojo#291]
I encounter this Rojo server crash several times a day at this point. It may have to do with using Vim instead of VS Code because I've noticed it more frequently lately when using Vim as my editor.

Example errors:

    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FsError { inner: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }, path: "C:\\Users\\macobr\\dev\\roblox\\phasic\\src/Client/Controllers\\CrateOpenUIController.lua~" }', src\libcore\result.rs:997:5
    note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FsError { inner: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }, path: "C:\\Users\\macobr\\dev\\roblox\\phasic\\src/Server/Modules\\Player.lua~" }', src\libcore\result.rs:997:5
    note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: FsError { inner: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }, path: "C:\\Users\\macobr\\dev\\roblox\\phasic\\src/Shared\\Pets.lua~" }', src\libcore\result.rs:997:5

I'm using Rojo 0.5.3

If it would be useful I can enable the noted environment variable to get a backtrace.

**Comment by LPGhatguy** [comment]
This is a really interesting bug, thank you for the report!

I believe Vim saves files with a `~` suffix for doing its "safe save" feature that some editors do. Your editor is writing to that file, deleting the old one, and renaming this one to the original name. Because Rojo has a chance to see that file being created, it might try to read it, only to find it's since been destroyed by Vim!

Most other editors, as far as I know, use a temporary directory for this feature instead of saving next to the original file. This might be why we haven't seen this bug before.

To work around this in the short term, you can tell Vim to write directly to files instead:

```vim
set nowritebackup
```

It's also possible that this bug does not occur (or looks different) in the current `master` branch of Rojo. You could try [downloading the latest prerelease](https://github.com/rojo-rbx/rojo/releases) to see if it has a similar bug, which would help us avoid regressing this bug in the future.

**Comment by FableRBX** [comment]
Thanks for your comprehensive response! I'll try both suggestions and let you know if the problem persists.

**Comment by LPGhatguy** [comment]
This issue should also no longer occur on Rojo master, which will see an alpha release soon.
