### ISSUE TITLE
Services with $path but not $className turn into folders

### ISSUE THREAD

**Issue by vocksel** [rojo-rbx/rojo#331]
I have partitions to ReplicatedStorage, ServerScriptService, and StarterPlayerScripts. I removed the $className field from all three. When running `rojo build`, ReplicatedStorage syncs normally, however ServerScriptService and StarterPlayerScripts both create new Folders instead of placing instances in the actual service.

**Comment by LPGhatguy** [comment]
I'm not sure if this one is a bug or something we should document. I'm going to make a couple assumptions about how your project is structured; let me know if I'm wrong here!

Rojo _always_ requires `$className` if it cannot intuit what the ClassName of an instance should be. One way that can happen is if your project node has `$path` defined. If `$path` is pointing to a folder, then the ClassName of the resulting instance will likely be `Folder`!

You should have a couple options to fix this:
1. Keep using `$className` when you're also using `$path`
2. Create `init.meta.json` files in the affected folders
3. Move any project nodes that require `$path` one level down. Instead of specifying all of `ServerScriptService` via `$path`, just specify some subset of it.

**Comment by vocksel** [comment]
You're exactly correct. Most of my partitions look like this:

```json
"ServerScriptService": {
	"$className": "ServerScriptService",
	"$path": "src/server"
},
```

So when $className is removed, it's assuming Folder. The reason this didn't happen with ReplicatedStorage is because every project node is nested within a subfolder, just as you mentioned.

Definitely doesn't sound like a bug then, just something that could probably do with documentation

**Comment by LPGhatguy** [comment]
After @Nezuo's comment in #13, I'm wondering if this is something we should actually change instead of document. It's not likely that you want a Folder when you're in the same spot in the DOM as a service would be. We can probably loosen the logic here to overwrite `Folder`, or maybe overwrite `Folder` in certain circumstances?

**Comment by kittenz** [comment]
I'm having the exact same issue, except this time Rojo crashes with
```
[ERROR] Rojo crashed!
[ERROR] This is probably a Rojo bug.
[ERROR]
[ERROR] Please consider filing an issue: https://github.com/rojo-rbx/rojo/issues
[ERROR]
[ERROR] Details: If $className and $path are specified, $path must yield an instance of class Folder
[ERROR] in file src\snapshot_middleware\project.rs on line 101
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
when trying to set $className to the correct service class name.

**Comment by LPGhatguy** [comment]
This is fixed up in master! We have much better error messages, and now this case is handled as expected.

**Comment by workframes** [comment]
I'm currently have the same issue.

**Comment by abepark26** [comment]
Visit http://localhost:34872/ in your browser for more information.
[ERROR librojo::change_processor] Snapshot error: ClassName for Instance "ServerScriptService" was specified in both the project file (as "ServerScriptService") and from the filesystem (as "Script").
        If $className and $path are both set, $path must refer to a Folder.
                             
        Project path: /Users/abepark26/Desktop/testRob/default.project.json
        Filesystem path: src/server
        
my default.project.json looks as follows:
```
{
  "name": "testGame",
  "tree": {
    "$className": "DataModel",
    "ReplicatedStorage": {
      "$path": "src/shared"
    },
    "ServerScriptService": {
      "$className": "ServerScriptService",
      "$path": "src/server"
    },
    "ServerStorage": {
      "$className": "ServerStorage",
      "$path": "/src/serverStorage"
    },
    "StarterPlayer": {
      "StarterPlayerScripts": {
        "Client": {
          "$path": "src/client"
        }
      }
    },
    "Worksp
```
