### ISSUE TITLE
Specify project type in .project.json

### ISSUE THREAD

**Issue by Jaguar-515** [rojo-rbx/rojo#336]
Say that I have a .project.json file that defines a place. However, when I try to build a model file, and when attempting to insert it into a place, it won't load. I then realize that I should be building a place, not a model.

Allowing a (possibly required?) project-type property in a .project.json file would let `rojo build` warn users that are trying to build a project type that isn't meant to be built in that project type (as said in my earlier example)

Here's what I think it should look in models & in places:
```json
// model
{
"name": "my-cool-model",
"project-type": "model"
}

// place
{
"name": "my-cool-place",
"project-type": "place"
}
```

**Comment by LPGhatguy** [comment]
I think the semantics of this idea are very good, though I think we already have the information in existing Rojo project files!

Specifically, Rojo already determines whether your project is a place or model file based on the class of the root instance in your tree. If it's a `DataModel`, we know it's a place, and otherwise it's a model.

We should make Rojo warn in the cases you describe using that information. A related issue is #113.

**Comment by LPGhatguy** [comment]
We now have a bit more code in Rojo that branches on whether your project describes a place or a model. I think we're in a good spot to close this issue.

If you have more suggestions in the future for what we could enable with this, feel free to comment on this issue again!
