### ISSUE TITLE
init.model.json not replacing folders

### ISSUE THREAD

**Issue by yaelvalle** [rojo-rbx/rojo#366]
When I add an init.model.json file into a folder it isn't converting the folder into a model and instead creates a model inside of the folder named init with all the contents I put inside

**Comment by LPGhatguy** [comment]
Hello, thanks for filing an issue.

What version of Rojo are you running? `init.model.json` files [were removed in Rojo 0.5](https://rojo.space/docs/0.5.x/guide/migrating-to-epiphany/#migrating-initmodeljson-files) and have been replaced with `init.meta.json` files. Because Rojo 0.4 is no longer supported, I would recommend checking out [the documentation for `.meta.json` files](https://rojo.space/docs/0.5.x/reference/sync-details/#meta-files), which is their replacement.

**Comment by yaelvalle** [comment]
Yea, I figured it out but now im having issues with creating meta files in general. I created one meta file but now when i create more they just dont get created
