### ISSUE TITLE
[Rojo-Warn] Disconnected from an error: Cannot Destroy() Terrain

### ISSUE THREAD

**Issue by qw1324** [rojo-rbx/rojo#385]
How to fix [Rojo-Warn] Disconnected from an error: Cannot Destroy() Terrain

**Comment by LPGhatguy** [comment]
Hi, thanks for filing an issue!

This likely happens because Rojo is trying to manage all of `Workspace`, but there's no entry for `Terrain` in your project file. One solution is to add `Terrain` to your project file, another might be to change your project file to only manage a portion of Workspace.

I'd like to have better error messages on this in the future. For now, the changes in recent versions of Rojo 6 will suffice.
