### ISSUE TITLE
If $className and $path are specified, $path must yield an instance of class Folder

### ISSUE THREAD

**Issue by ovarflode** [rojo-rbx/rojo#400]
build 6.0.0-rc.3

Rojo thinks that a folder isn't a folder. This is my first time having that issue ever since I updated to 6.X.X.
Cannot sync my scripts now and therefore cannot meet my deadlines because of this.

Putting a subfolder will turn the folder into a localscript in roblox studio.

![jsoncode](https://user-images.githubusercontent.com/61893206/109231523-66472f00-778c-11eb-89bd-574dff0413db.png)
![explorer](https://user-images.githubusercontent.com/61893206/109231524-66472f00-778c-11eb-993e-b072611217d1.png)
![error](https://user-images.githubusercontent.com/61893206/109231527-66472f00-778c-11eb-8a84-8ae6aff75aa3.png)

**Comment by Nolan-O** [comment]
I believe you need to rename `Init` in `Init.client.lua` to something else so that it doesn't treat `ReplicatedFirst` as a script with children. I was stuck on this trying to convert from the default project file since its augmentations to the default place layout make no sense. I'm not sure what purpose the default scripts serve except to eventually cause this issue.

**Comment by Kampfkarren** [comment]
It's `init` that makes it a script, not `Init`. If that fixes it, that's weird.

**Comment by ovarflode** [comment]
Very strange. Renaming it to `init.client.lua` will omit anything parented under `_FirstPackage`, and `Init.client.lua` won't solve the problem. However, renaming it to `_Init.client.lua` or something (that I would think) doesn't sound like a default filename and everything is working fine.

Thanks a lot for your guidance with this issue.
