### ISSUE TITLE
rojo needs to account for BrickColor properties using int32 in XML format

### ISSUE THREAD

**Issue by NobleDraconian** [rojo-rbx/rojo#407]
Currently, as of `7.0.0-alpha.2`, rojo errors when trying to 'compile' any object that has a `BrickColor` property. This is because `BrickColor` properties are stored as an int32 in XML format, but rojo does not account for this.
![image](https://user-images.githubusercontent.com/26460940/110717126-76bcc800-81d6-11eb-808e-3e38decf7a66.png)
![image](https://user-images.githubusercontent.com/26460940/110717135-7ae8e580-81d6-11eb-8297-02920abd6635.png)

**Comment by Dekkonot** [comment]
This isn't an issue with just AlignOrientation; BrickColor is stored as an Int32 in the XML format and it looks like the conversion to BrickColor isn't being handled properly when trying to build to the binary format.

**Comment by NobleDraconian** [comment]
Oh, I'll update my title and post accordingly then.

**Comment by LPGhatguy** [comment]
This should be fixed in the master branch; see https://github.com/rojo-rbx/rbx-dom/commit/275ac22e33f6fc0ebc7fce94c84735d626cf20e4 and https://github.com/rojo-rbx/rbx-dom/commit/0995c51749869ac65279caeeff3a2dcaad41ca4a.

We probably should fix rbx_xml to decode these values as `BrickColor` values instead of as `Int32`, but at least the encoding portions of both rbx_xml and rbx_binary should no longer have issues.
