### ISSUE TITLE
Meta Files for Tools Grip property causes Snapshot error

### ISSUE THREAD

**Issue by cskeogh** [rojo-rbx/rojo#430]
I created a file `init.meta.json` identical to the documentation [Meta Files for Tools](https://rojo.space/docs/6.x/sync-details/#meta-files):

```json
{
    "className": "Tool",
    "properties": {
        "Grip": [
            0, 0, 0,
            1, 0, 0,
            0, 1, 0,
            0, 0, 1
        ]
    }
}
```

Results in error:
```
[ERROR] Snapshot error: File contained malformed init.meta.json data: init.meta.json
        
        Caused by:
            data did not match any variant of untagged enum UnresolvedValue at line 10 column 5
```

I am using Rojo v7.0.0-alpha.4

**Comment by LPGhatguy** [comment]
Hello, thank you for the report. This is related to #421.

We have been working on tweaking Rojo's JSON property format to make it easier to use. This is going to be a breaking change from 6.x, but should be for the best. Unfortunately, the 7.0 alphas are in kind of an awkward middle state. Fixing this (and releasing a tool for people to migrate their projects) is the last remaining blocker for Rojo 7.0's stable release.

I recently introduced [some tests for the JSON property shorthand syntax](https://github.com/rojo-rbx/rojo/blob/17fdd18c55229345d0efd095af1f1ee09f5f2f7b/src/resolution.rs#L242-L272). We also have a more explicit property syntax. Not all property types have a shorthand version.

In Rojo 7.0.0-alpha.4, we don't have a shorthand syntax to specify CFrame values. You should be able to specify a CFrame values using the explicit syntax like this:

```json
{
    "className": "Tool",
    "properties": {
        "Grip": {
            "Type": "CFrame",
            "Value": {
                "Position": [0, 0, 0],
                "Orientation": [
                    [1, 0, 0],
                    [0, 1, 0],
                    [0, 0, 1]
                ]
            }
        }
    }
}
```

This is obviously not ideal. We are on track to update the explicit value syntax in the next 7.0 alpha with this:

```json
{
    "className": "Tool",
    "properties": {
        "Grip": {
            "CFrame": {
                "position": [0, 0, 0],
                "orientation": [
                    [1, 0, 0],
                    [0, 1, 0],
                    [0, 0, 1]
                ]
            }
        }
    }
}
```

Note that `Type` and `Value` are gone and the casing of values is different. We could also reintroduce the same shorthand syntax for CFrame values, which would make your original model work:

```json
{
    "className": "Tool",
    "properties": {
        "Grip": [
            0, 0, 0,
            1, 0, 0,
            0, 1, 0,
            0, 0, 1
        ]
    }
}
```

I had originally removed the CFrame shorthand during the port to rbx_dom_weak v2 because I didn't remember that people hand-wrote CFrame values for `Tool.Grip`. Reintroducing it for the next release feels like an easy change that we can make.

**Comment by LPGhatguy** [comment]
Sorry for the long turnaround on this, should be good to go on the master branch.
