### ISSUE TITLE
Ignore folder path not existing

### ISSUE THREAD

**Issue by RigidStudios** [rojo-rbx/rojo#474]
`$path referred to a path that could not be turned into an instance by Rojo` currently crashes Rojo when a folder does not exist.

In my current situation I have no `src/shared` folder as I deleted the default script inside of it, published to GitHub, and GitHub deletes any file-less folders, so upon clone I was left without the folder. It is only a minor inconvenience but also one that should not be all that difficult to fix.

**Comment by LPGhatguy** [comment]
Referencing a path that does not exist being an error is intentional. We've improved the error message in newer versions of Rojo. We want this to stay an error so that typo'd path names turn into errors instead of staying hidden.

There is an open PR, #472, that lets users opt into the behavior you are looking for.

**Comment by sasial-dev** [comment]
You can use .gitkeep in the folder as well to keep it :)
