### ISSUE TITLE
Plug-in's disconnect button ("X") may be mistaken for error indicator

### ISSUE THREAD

**Issue by ejm554** [rojo-rbx/rojo#554]
One of my developers mistook the disconnect button ("X") in the plug-in for an error indicator. When they clicked it, presumably to see information about the error, it disconnected them from the Rojo server. Despite the "Connect" button that replaced the "X", they didn't notice that they were no longer connected.

![image](https://user-images.githubusercontent.com/26723535/173254067-0506f88a-cb42-4af7-858e-bac3ea0feac7.png)

---
### Possible Solutions
- Display a tooltip or expansion panel, e.g., "Disconnect from server," when hovering over the "X".
- Revert to the button style used in version 0.5.0-alpha.11, shown below, that had a "Disconnect" label.
- Replace the red with a color that is less likely to be mistaken for an error indicator.
- Replace the "X"  symbol with a more illustrative one, such as those shown below.

    ![image](https://user-images.githubusercontent.com/26723535/173255060-fa77b785-48eb-405d-8d9e-da9bc20442fb.png)

    ![image](https://user-images.githubusercontent.com/26723535/173255323-f6fa130f-8a98-41ea-b2d0-284409291439.png)

**Comment by PoolloverNathan** [comment]
In my opinion, the right disconnect icon looks even more like an error. My vote is for a 'Disconnect' button that has the style of the 'Settings' button.

**Comment by boatbomber** [comment]
I'm not going to mark this as closed just yet, because I believe there's still improvements to be made here, but we have made good progress on this.

For one, there are tooltips now.
![image](https://github.com/rojo-rbx/rojo/assets/40185666/f3dec4d4-40c1-4e6d-99ef-79b3c923d8ca)

Secondly, there's sync info which makes it more clear that this is the connected page.
![image](https://github.com/rojo-rbx/rojo/assets/40185666/5d8b9467-c141-467a-b794-4089083694fb)
