### ISSUE TITLE
Send viewport notification when a game is running without being connected (or a setting)

### ISSUE THREAD

**Issue by Logic-Mastermind** [rojo-rbx/rojo#586]
Sometimes, but not too commonly, I'm running my game without Rojo being connected and not realising, spending some time attempting to troubleshoot the errors that I thought I had already fixed.

I think it's worth adding a visual indicator that tells us when we're not connected to Rojo, to prevent this type of issue. And for the many smart people who always double check, unlike me, there can be a setting to turn it on/off.

**Comment by boatbomber** [comment]
The plugin toolbar button shows a little link icon when the plugin is connected, as a way to expose connected status without having the widget open.

**Comment by Logic-Mastermind** [comment]
> The plugin toolbar button shows a little link icon when the plugin is connected
Yeah that's right, however we're not always on the plugin tab

**Comment by boatbomber** [comment]
Hm. Perhaps, when you press play, it outputs a little warning if it finds an active serve that it's not connected to? That assumes you've already configured the port, cuz we won't be scanning every port.

**Comment by boatbomber** [comment]
Well, I got a prototype working.
![demo](https://user-images.githubusercontent.com/40185666/180619534-f5d68206-ace2-4cc3-bd2f-62b93b799af2.png)

In making this, I discovered some interesting design and limitation problems.
1) Client can't make Http requests, so you'll only see the notification if you switch to server view in Accurate Play Solo (note the green outline in my demo image). You'll see the warning in the output, at least.
2) It'll happen *every* time you play, since obviously it starts out not connected. This is very annoying.

Perhaps a little info on the connect page to let you know it found a serve? This doesn't really solve the problem though, as you may not be looking there or even have the widget open.
![image](https://user-images.githubusercontent.com/40185666/180619703-cf946590-2fc0-48ac-be45-c0df790b828b.png)

This issue needs more thought. Anyone want to weigh in?

**Comment by sasial-dev** [comment]
Is it worth just waiting for https://github.com/rojo-rbx/rojo/pull/468 to be complete?

**Comment by boatbomber** [comment]
That won't help the common case of forgetting to connect in Edit mode, @sasial-dev. That auto connects in Run mode when you've already connected in Edit mode.

**Comment by LPGhatguy** [comment]
I'm not sure it's valid to nag the user to connect whenever there's a session running at all.

I think Rojo probably has a deeper workflow issue here. We should make the process of starting Rojo, opening Studio, and connecting a seamless operation. A user should be able to double-click a Rojo project and be off to the races.

Small fixes like this might solve some users forgetting to connect at the expense of users who _don't_ want to connect getting a lot of unnecessary noise.

**Comment by boatbomber** [comment]
My solution in PR #588 allows them to hit ignore, so it would not be a ton of noise at least, just the one nudge. I do agree that we should have a smoother flow overall, but this can still potentially be a valid short term measure.

**Comment by LPGhatguy** [comment]
I think that even with an ignore switch, this is a feature that's in the wrong direction. Ignoring isn't persisted in any way, so it'll still pop up at least once. Storing which places have ignored the prompt diminishes the value of the feature, but not storing them still annoys people we don't need to ignore.

Instead of this band-aid, let's think about what the longer term workflow looks like for Rojo.
