### ISSUE TITLE
Is there a way to ignoreUnknownInstances on every instance?

### ISSUE THREAD

**Issue by L3G5ND** [rojo-rbx/rojo#632]
If there is a way then I suggest making ignoreUnknownInstances on every instance set to true by default, that's just my opinion though.

**Comment by LPGhatguy** [comment]
Rojo has `ignoreUnknownInstances` as an option because it's sometimes useful for projects that have unmanaged instances in awkward places. It's a targeted tool for solving a specific issue.

Users should definitely not turn `ignoreUnknownInstances` on for every instance. It stops Rojo from knowing when instances should be deleted and projects that rely on it a lot are very hard to reason about.
