### ISSUE TITLE
Rojo `build` does not respect `WeldConstraint.Enabled`

### ISSUE THREAD

**Issue by NobleDraconian** [rojo-rbx/rojo#645]
Currently, as of `v7.2.1` (e482aba030aa1661bc3bd0d80dab85df6fca2fcf), the `build` command does not respect `WeldConstraint.Enabled`, resulting in all `WeldConstraint` instances that are generated having their `Enabled` properties set to `false`.

However, the `serve` command *does* respect `WeldConstraint.Enabled`.

I've attached a video of the problem occurring, as well as a repro with repro steps.

Repro steps:
1) Download & extract `RojoBug_Repro.zip`
2) Generate a place file via the `build` command, `rojo build default.project.json -o PlaceFile.rbxl`
3) Open the place file, and look at the weldconstraints in `ReplicatedStorage.Tools.SledgeHammer`. Observe that `Enabled` is set to `false` on them.
4) Right-click `Workspace`, click "insert from file..." & insert `SledgeHammer.rbxmx` into the workspace. Observe that all of the weldconstraints have `Enabled` set to `true`.
5) Close the place file
6) Delete `Hammer.rbxmx`
7) Re-generate the place file, `rojo build default.project.json -o PlaceFile.rbxl`
8) Open the place file, and look at the weldconstraints in `ReplicatedStorage.Tools.SledgeHammer`. Observe that `Enabled` is set to `true` on all of them (as expected)

https://user-images.githubusercontent.com/26460940/199100588-4db0d436-0e31-4910-ad35-e3a30b3d6dfb.mp4

[RojoBug_Repro.zip](https://github.com/rojo-rbx/rojo/files/9905203/RojoBug_Repro.zip)

**Comment by Anaminus** [comment]
In v0.468, [CanSave of WeldConstraint.Enabled was changed to false](https://robloxapi.github.io/ref/class/WeldConstraint.html#member-Enabled), meaning that the property itself is no longer serialized, and the data is stored by other means. In this case, that appears to be the "State" property.

The reason Rojo isn't interpreting this correctly is because it doesn't know about this relationship between the properties. Usually, this could be patched (i.e. [weld-constraint.yml](https://github.com/rojo-rbx/rbx-dom/blob/master/patches/weld-constraint.yml)). Unfortunately, the relationship between these properties is more complex than usual, and currently cannot be represented by a patch.

Some information about the State property: It is an `int` with one of several states that depend on certain conditions:

State | Condition
-----:|----------
0     | Enabled == false
1     | Enabled == true and (Part0 == nil or Part1 == nil)
2     | ???
3     | Enabled == true and (Part0 ~= nil and Part1 ~= nil)

Additionally, WeldConstraint appears to be (possibly incorrectly) initialized with State==3, despite not being attached to any parts.

**Comment by kennethloeffler** [comment]
Can't repro as of 7.4.3, so I'm closing this issue. Please let me know if you're still seeing this problem!
