### ISSUE TITLE
Prompt to resume syncing when entering place where you previously used Rojo

### ISSUE THREAD

**Issue by Elttob** [rojo-rbx/rojo#652]
Rojo has a very real issue with communicating its sync status to users. Aside from the plugin icon being different somewhere in the Plugins tab, there is absolutely nothing to suggest that anything isn't syncing, especially if you save regularly to Roblox. This is because you're still able to play the place and everything *looks* like it's there, where in reality because Rojo is disabled, no new changes have synced. This has led to *hours* of wasted time on our development team hunting down bugs that were already fixed or wondering why debug prints were not showing.

The problem here is that, being a fully managed Rojo project, we expect syncing to be on all of the time. However, if syncing is off, we aren't told about it. Primarily this is a problem whenever Studio is first opened for the day, or restarted during the day (which is now commonplace due to recent stability issues).

Talking about this with my colleague, they note that the maintainers here have previously pushed back on ideas to allow Rojo to scan and automatically connect to existing Rojo sessions on the user's computer, which *does* still have the failure case of not starting Rojo in your external editor/terminal. I will **not** propose this. Instead, I propose an alternative.

When you have run Rojo in a place previously, it is likely you will run Rojo in that place next time you open it. With this insight, I propose that Rojo show a prompt as a notification in this scenario. The prompt's purpose is twofold:

- remind you that you have run Rojo in this place previously, so you should probably run it this time too
- give you the option to attempt to connect using the same IP/port settings as last time
- alternatively, allows you to dismiss the prompt, which will cause it to no longer show in future until you use Rojo there again

This serves multiple purposes:

- in the case you have completely forgotten about Rojo, it will remind you to start it in your external editor/terminal, then gives you a one-click option to resume syncing
- in the case you have started Rojo in your external editor/terminal, but have forgotten that the Studio half requires starting separately, it will give you a one-click option to resume syncing properly
- in the case you already remembered and intended to open Rojo to resume syncing, reduces the time it takes to invoke the action you already planned to do
- in the exceedingly rare case you did not want to resume using Rojo, the prompt can be dismissed right away

It would be a good idea to put this behind a setting of some kind, so on the off-chance this is annoying for someone's specific workflow, it can be turned off.

**Comment by boatbomber** [comment]
I think off by default might make this an easier pill to swallow.

**Comment by OscarWoHA** [comment]
I appreciate the clarification. On a second read, I now understand that your proposal is more about making sure the user is aware that Rojo is in fact _not connected_ (which is a common problem, the amount of times I've wondered why things aren't changing is honestly embarrassing) rather than a way to minimize the UX-"friction" of the syncing itself.

**Comment by OscarWoHA** [comment]
> > An opt-in automatic reconnect with Rojo would be a game-changer!
> > I've also been wondering why Rojo doesn't have an "Uh-oh! The project you're trying to sync looks completely different than what's on disk. Are you sure?" for a while, which would help mitigate any risk this could potentially introduce.
> > I definitely like your proposal though, and as @boatbomber said it would probably have to launch in an off-state at first.
> 
> The idea here is that it's explicitly _not_ automatic though :)
> 
> The user still has to decide to invoke Rojo - it won't automatically scan for any open Rojo connections, since that's already been historically unpopular. I've reworded a bit of my post to reflect what I mean better.


I appreciate the clarification. On a second read, I now understand that your proposal is more about making sure the user is aware that Rojo is in fact not connected (which is a common problem, the amount of times I've wondered why things aren't changing is honestly embarrassing) rather than a way to minimize the UX-"friction" of the syncing itself.

**Comment by boatbomber** [comment]
I think this is a really clean way to handle a lot of important cases in a non intrusive way, and best of all the technical implementation seems very straight shot since we already store last sync address per place (in order to avoid making users retype their host and port every time) which we can use as a signal for this.

I plan to start on it this weekend, so if anyone has last minute comments please speak up!

**Comment by boatbomber** [comment]
I have a working implementation of this now! (I didn't feel like waiting for the weekend.) Going to polish up before making a PR.

![image](https://github.com/rojo-rbx/rojo/assets/40185666/ccdfddf2-a63f-420c-bc18-a6e3d6455bba)
