### ISSUE TITLE
Parallel Luau Support

### ISSUE THREAD

**Issue by KevinWh0** [rojo-rbx/rojo#653]
Rojo v7 is missing support for Parallel Luau, and it would really help for computationally heavy tasks.

**Comment by boatbomber** [comment]
Can you elaborate what you mean by missing support?

If you mean missing adoption (ie: the Rojo plugin is not using parallel Luau) then that is because Rojo's main bottleneck is not heavy computation, it's the act of creating Instances and setting Instance properties. Those actions cannot be done in a parallel context, so adopting it would make effectively no difference to Rojo's performance.

**Comment by boatbomber** [comment]
If you mean support for creating Actors, you can use model json files to create them like anything else.

https://rojo.space/docs/v7/sync-details/#json-models
