### ISSUE TITLE
Rojo sync does not respect selected Instances

### ISSUE THREAD

**Issue by hello-42** [rojo-rbx/rojo#659]
Rojo doesn't reflect changing $properties of selected Instances in Roblox Studio. 

![image](https://user-images.githubusercontent.com/63469196/225768353-0b4894e1-cb99-4e39-ba92-e46d59a2c008.png)

Repro steps:
1. Open a rojo project and select an Instance in Roblox Studio's Explorer, where that Instance's properties are defined with the $properties JSON schema in a project file.
2. Attempt to change any of the properties within $properties that correlate to that Instance.

In the above image, I have "Baseplate" selected from a fresh file from `rojo init & rojo build -o place.rbxl & rojo serve`. After selecting Baseplate, I attempted to change Baseplate's "Anchored" property to `false` in it's $properties JSON. That warning comes after the project file is saved & synced with the rojo server, and the property changed does not update.

**Comment by boatbomber** [comment]
I'm able to repro this warning, but it *does* update the property. When I set the baseplate to anchored: false, it does apply correctly.

The Rojo Metadata warning is unrelated to property updates. Changing the json resends ignoreUnknownInstances.
The fact that it fails is because it's an unimplemented TODO for the last several years.

![image](https://github.com/rojo-rbx/rojo/assets/40185666/680416e5-dbad-4ebf-876b-f460b5d3876a)

**Comment by boatbomber** [comment]
Selection has nothing to do with this, it's just an unimplemented thing. You can safely ignore it.
