### ISSUE TITLE
the studio plugin for rojo should default to `127.0.0.1`, not `localhost`

### ISSUE THREAD

**Issue by madeline-xoxo** [rojo-rbx/rojo#664]
for compatibility's sake (e.g. running roblox under flatpak, where `localhost` does not resolve to `127.0.0.1`), the plugin for studio should default to `127.0.0.1` instead of `localhost`.

**Comment by LastTalon** [comment]
That doesn't seem correct as a default. That happens because you likely don't have a localhost protocol handler in flatpak. You can always use the loopback address `127.0.0.1` yourself, but for handling the localhost protocol where it may not be that particular address it would break things and lower compatibility.

It seems like perhaps a more correct solution to the problem you're encountering would be to be able to set your personal default connection. Then you'd configure it once and connect that way every time.
