### ISSUE TITLE
Can not sync starterplayer and starterplayerscripts in rojo, server also disconnected

### ISSUE THREAD

**Issue by LokiGitHubb** [rojo-rbx/rojo#752]
I just started using rojo, and i tried to add starter player to the sync tree. But, when i save, it disconnects the server and throws this err:
![image](https://github.com/rojo-rbx/rojo/assets/140853603/ba6e096e-5273-443f-bc79-5e14d50346e3)
 Heres my settings:
`{
  "name": "Tank Pack",
  "tree": {
    "$className": "DataModel",
    "ServerStorage": {
      "$className": "ServerStorage",
      "$ignoreUnknownInstances": true,
      "$path": "src/ServerStorage"
    },
    "Workspace": {
      "$className": "Workspace",
      "$ignoreUnknownInstances": true,
      "$path": "src/Workspace"
    },
    "StarterPlayer": {
      "$className": "StarterPlayer",
      "$path": "src/StarterPlayer",
      "StarterPlayerScripts": {
        "$className": "StarterPlayerScripts",
        "$path": "src/StarterPlayerScripts"
      }
    }
  }
}
`

**Comment by Barocena** [comment]
it tries to delete StarterCharacterScripts since you sync starterplayer
adding StarterCharacterScripts should fix the issue
```json
{
  "name": "Tank Pack",
  "tree": {
    "$className": "DataModel",
    "ServerStorage": {
      "$className": "ServerStorage",
      "$ignoreUnknownInstances": true,
      "$path": "src/ServerStorage"
    },
    "Workspace": {
      "$className": "Workspace",
      "$ignoreUnknownInstances": true,
      "$path": "src/Workspace"
    },
    "StarterPlayer": {
      "$className": "StarterPlayer",
      "$path": "src/StarterPlayer",
      "StarterCharacterScripts": {
        "$className": "StarterCharacterScripts"
      },
      "StarterPlayerScripts": {
        "$className": "StarterPlayerScripts",
        "$path": "src/StarterPlayerScripts"
      }
    }
  }
}
```

**Comment by Dekkonot** [comment]
We can change Rojo to not try to delete Services implicitly, though that would be a new feature and not a bug fix. Right now, this is expected behavior; what Barocena suggested does in fact work.

As an addendum though, you don't need to specify the `$className` of any of these. Services, `StarterPlayerScripts`, `StaterCharacterScripts`, and are special cased so that it assumes their classname if it isn't specified. In the next release, this will also include `Terrain`.
