### ISSUE TITLE
Allow changing sync popup mode between never, always & place-id based

### ISSUE THREAD

**Issue by PysephWasntAvailable** [rojo-rbx/rojo#773]
When quickly adding patches or hotloading changes, the 'Sync changes to project X' becomes strenuous and hinders the workflow when quickly implementing changes. Thus, being able to hide the popup either permanently, or based on place-id would address these workflows.

Perhaps some consideration should also be made for separating small and 'big' changes, in case an incoming change affects too much of the codebase in a suspicious manner.

**Comment by Kampfkarren** [comment]
To be clear "by place ID" for me means "if I have servePlaceIds set, and this is a valid place, let me skip the warning"

**Comment by Dekkonot** [comment]
I think it's fair to support both "turn off for this game" and "skip for known PlaceId" as options.

I worry it might be a foot gun to support turning it off in its entirety though. It feels like the sort of thing someone might turn off immediately when prompted because they think it's annoying, but having it for new games is probably worth it.

Related: this will need special handling for the places listed in [this file](https://github.com/rojo-rbx/rojo/blob/master/plugin/src/ignorePlaceIds.lua) because they're not unique. What would the preferred behavior be for them?

**Comment by boatbomber** [comment]
Thanks for bringing up this issue, I agree the confirmation can be a bit noisy in workflows that do rapid connect-disconnects.

I don't think disabling it is a good solve though, that's just avoiding addressing the root issue here.

I propose we have the following options for confirmation behavior:
- Always
   The current behavior, always confirms before syncing
- Large Changes
   Only confirm when there are more than X changes (we can tune as needed)
- Initial
   For a given place, each project file being served will only confirm once in a given Studio session (This resolves the hot workflows of constant connect/disconnect, while still protecting against syncing a different project)
- Unlisted PlaceId
   Only confirms for syncs into places that do not match the set servePlaceIds (If none are specified, behaves as Always)

**Comment by boatbomber** [comment]
> Related: this will need special handling for the places listed in [this file](https://github.com/rojo-rbx/rojo/blob/master/plugin/src/ignorePlaceIds.lua) because they're not unique. What would the preferred behavior be for them?

I don't think they need special handling at all, actually. When using the Unlisted PlaceId mode, I would expect a confirmation when I'm syncing to a template place instead of my published and listed place.
