### ISSUE TITLE
Use of the name property of .rbxmx or .rbxm files instead of file names

### ISSUE THREAD

**Issue by VillaErnest** [rojo-rbx/rojo#922]
It seems like when you replicate a .rbxmx or .rbxm files, it uses their actual file names instead of the name property of the model.
It might be trivial, but I do think it makes more sense for the property names to take precedence over the file name.

Specially, developers might want some models to have the same name, but this is not possible since you can't have same name for files in the file system.

**Comment by Dekkonot** [comment]
This is unlikely to happen because it'd be a breaking change. I understand the use case but it's something we're probably stuck with for now.

**Comment by kennethloeffler** [comment]
This is pretty fundamental to the way Rojo works and cannot be changed without seriously breaking users, which is not worth whatever benefit it'd bring, so I'm going to close this issue. 

However, the use case of "I want to have instances named the same thing" is totally valid, and we've thought a little bit about ways we can support that. If you'd like, you can open a new issue that more describes this use case, rather than how it should technically be supported.
