### ISSUE TITLE
When Rojo fails to sync a model (such as MeshParts), it deletes what is already in studio

### ISSUE THREAD

**Issue by tapple** [rojo-rbx/rojo#924]
1. Disconnect studio from rojo
2. In studio, add a mesh model to a folder managed by rojo
3. export that mesh model as a rbxm at the same location in the filesystem
4. reconnect studio to rojo

Actual behavior: rojo fails to sync, and deletes the whole model in studio
Expected behavior: rojo fails to sync the mesh id, but syncs everything else, and the model remains as is in studio

**Comment by kennethloeffler** [comment]
I'm having trouble reproducing this - what does your project file look like when this happens?

**Comment by tapple** [comment]
I can't reproduce this anymore either. Closing

**Comment by lcd11001** [comment]
I have the same issue when trying export CUSTOM MODEL (including paints, hat1, shirt) to ServerStorage/Charaters/xxx.rbxmx format.
After reconnect Rojo, it shows warning message: "Synced xx seconds ago, but xxx changes failed to apply" as attachment.
This issue make my model turn into white blocks instead of my custom model.
Hope Rojo fix this issue soon.
Thank you!

<img width="801" alt="Image" src="https://github.com/user-attachments/assets/51163193-20ff-4991-b57e-f1671257d840" />
