### ISSUE TITLE
Cannot select Studio Rojo plugin error text to Copy Paste

### ISSUE THREAD

**Issue by skwog** [rojo-rbx/rojo#939]
Studio Rojo plugin error text says "This is a bug in Rojo. Please file an issue:"

But the error output text is not selectable, requiring work arounds in order to file an issue as requested.

**Comment by Dekkonot** [comment]
I'm not sure if we can actually support this since I don't know if Roblox GUIs actually support selectable text. I believe we emit the same log in the output though.

I will double check this and make sure it's true. Then we can probably change the plugin's message to tell people to check the output.

**Comment by boatbomber** [comment]
Did something recently break? We've had copyable errors for years and haven't modified the code. Are you on a very outdated version?

https://github.com/rojo-rbx/rojo/pull/614
