### ISSUE TITLE
SurfaceAppearance.Color might be set to (0,0,0) by default instead of (1,1,1) causing black SurfaceAppearances

### ISSUE THREAD

**Issue by beam-roblox** [rojo-rbx/rojo#942]
The new SurfaceAppearance.Color API will get released soon and we received [this bug report](https://devforum.roblox.com/t/jailbreak-custom-character-turned-shiny-black-no-texture/3075563) yesterday that makes us believe Rojo might be setting the default value of this property at (0,0,0). This would multiply all SurfaceAppearances generated by black rendering them entirely black. The correct default value for SurfaceAppearance.Color is (1,1,1).

**Comment by Dekkonot** [comment]
Howdy. This is an underlying problem with our reflection database being out of date. I've left a response to the report [here](https://devforum.roblox.com/t/surfaceappearance-not-displaying-correctly/3075588/12?u=dekkonot) that should hopefully provide a bit more info.

This isn't really actionable on our end right now because it requires us to make a new release, which is easier said than done. I'm going to leave this open until I talk with my fellow maintainers about what our plans are and I'll update it here.

**Comment by Dekkonot** [comment]
Howdy. Quick update on this one. We're moving forward with publishing Rojo v7.4.2 soon (should be later today) so this issue should be resolved after that. Going to close this issue.

**Comment by beam-roblox** [comment]
Thank you so much Dekkonot! :)
