### ISSUE TITLE
intellij/pycharm jetbrains ide integration

### ISSUE THREAD

**Issue by khaki-git** [rojo-rbx/rojo#976]
are there any plans to add support/extension for the [intellij ide platform](https://www.jetbrains.com/ides/)? i use it more often then visual studio code and find it more productive

**Comment by kennethloeffler** [comment]
The Rojo team probably isn't going to do this in the foreseeable future, as we're not aware of a large number of users using JetBrains editors to work on Roblox code, and work is currently focused on core areas of Rojo, rather than editor integration. 

But do feel free to work on this on your own - I think we'd be totally want to give you a shout-out on [rojo.space](https://github.com/rojo-rbx/rojo.space), Rojo's documentation site!

**Comment by cbasitodx** [comment]
Check out this repo me and my friends been working on: https://github.com/jnegrete2005/rojo-intellij-integration
